import Ember from 'ember';

export default Ember.Controller.extend({
  actions: {
    submitSignUp() {
     var signup = this.store.createRecord('member', {
          username: this.username,
          email: this.email,
          password: this.password,
          bio: this.bio,
          template: this.template,
          theme: this.theme,
          profilePic: this.profilePic,
          blogPic: this.blogPic,
          facebook: this.facebook,
          twitter: this.twitter,
          instagram: this.instagram


      });
      var self = this;
      signup.save().then(function(member) {
        self.transitionToRoute('login')
      });
//       var gecko = this.store.createRecord('gecko', {
//     date: new Date(),
//     type: "gecko",
// });
//
// /*
//    Here ember-data expects a payload like this:
//         gecko: {id: 1, date: "", type: "gecko"}
//    The id is generated by your backend
// */
// gecko.save().then(function(gecko){
//     console.log(gecko.get('id'))
// })
    },
  }
});
